### ISSUE TITLE
Things to learn for js developers

### ISSUE THREAD

**Issue by MichalPaszkiewicz** [jaicab/frontend2engineer#1]
Aside from what you have written so far:

Browser APIs! There are so many of them! If anyone ever asks me, I always recommend learning at least:
localstorage
canvas
websockets

If you want to go really deep and become a bit more advanced, these are more challenging:
webRTC
webGL
web audio

Modern frameworks/libraries that are becoming a must in the js world are:
Backbone
Angular
React

If you are more interested in having fun, I would take a look at:
THREE.js
Phaser

Great tools for creating cross-platform apps:
Electron
Cordova
Ionic (if you use angular)

And obviously looking into APIs you are likely to very often use in business will always be a plus. A great place to start are the Google APIs (maps, analytics etc)

**Comment by jaicab** [comment]
Thanks! I'll add these to the list. MVC frameworks are already in there.
I think browser APIs / third party APIs are good although not necessarily skills, but things you can pick up once you know your way around JS.

**Comment by jaicab** [comment]
All added :)
